# .github/workflows/build-stable.yml
name: Build Windows Executable

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt

    - name: Install Playwright
      run: |
        python -m playwright install chromium

    - name: Build with Nuitka
      run: |
        cd source
        python -m nuitka --standalone --onefile --windows-console-mode=disable --include-package=icalendar --include-package=keyring --include-package=pandas --include-package=playwright --include-package=pytz --include-package=greenlet --include-package=pyee --include-package=websockets --output-filename=../SchoolAuto.exe main.py

    - name: Verify build
      run: |
        echo "构建完成，检查文件..."
        ls -la SchoolAuto.exe
        echo "文件大小: $(stat -c%s SchoolAuto.exe) bytes"

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SchoolAuto-Windows
        path: SchoolAuto.exe
        retention-days: 30