# .github/workflows/build.yml
name: Build Windows Executable

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install nuitka

    - name: Install Playwright and verify browser path
      run: |
        python -m playwright install chromium
        echo "Playwright browsers installed at:"
        dir "%USERPROFILE%\.cache\ms-playwright" /s

    - name: Build with Nuitka (without browser inclusion)
      shell: cmd
      run: |
        cd source
        python -m nuitka --standalone --onefile --windows-console-mode=disable --include-package=icalendar --include-package=keyring --include-package=pandas --include-package=playwright --include-package=pytz --include-package=greenlet --include-package=pyee --include-package=websockets --output-filename=../SchoolAuto.exe main.py

    - name: Verify build
      run: |
        if exist "SchoolAuto.exe" (
          echo "✅ 构建成功！"
          dir SchoolAuto.exe
        ) else (
          echo "❌ 构建失败"
          exit 1
        )

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SchoolAuto-Windows
        path: SchoolAuto.exe